	/* Dplus = */	find(3,"+");
	/* Dminus = */	find(3,"-");
	/* Dmult = */	find(3,"*");
	/* Ddiv = */	find(3,"/");
	/* Dmod = */	find(3,"mod");
	/* Dband = */	find(3,"/\\");
	/* Dbor = */	find(3,"\\/");
	/* Dxor = */	find(3,"^");
	/* Dshiftl = */	find(3,"<<");
	/* Dshiftr = */	find(3,">>");
	/* Dland = */	find(3,"and");
	/* Dlor = */	find(3,"or");
	/* Dene = */	find(3,"=\\=");
	/* Deeq = */	find(3,"=:=");
	/* Dlt = */	find(3,"<");
	/* Dle = */	find(3,"=<");
	/* Dgt = */	find(3,">");
	/* Dge = */	find(3,">=");
	/* Dis = */	find(3,"is");
	/* Dif = */	find(2,"if");
	/* Dcomma = */	find(3,",");
	/* Dsemi = */	find(3,";");
	/* Dtrue = */	find(1,"true");
	/* Darrow = */	find(3,":-");
	/* Dcall = */	find(2,"call");
	/* Ddot = */	find(3,".");
	/* Dnil = */	find(1,"[]");
	/* DERROR = */	find(0,"ERROR");
	/* D_cmd = */	find(3,"$cmd");
	/* D_ = */	find(0,"_");
	/* Dbrace = */	find(2,"{}");
	/* Duminus = */	find(2, "-");
	/* Dbnot = */	find(2, "\\");
	/* Dsave = */	find(2, "save");
	/* Drest = */	find(2, "restore");
	/* D_dbab = */	find(2, "$db_onabort");
